name: GPT Code Reviewer

on:
  pull_request:
    paths:
      - '**/*.swift'
      - '**/*.h'
      - '**/*.m'
      - '**/*.cpp'
      - '**/*.java'

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install OpenAI library
      run: pip install openai

    - name: Run GPT Code Review
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
        while IFS= read -r file; do
            echo "Reviewing file: $file"
            review=$(python3 gpt_code_review.py "$file")
            gh pr comment ${{ github.event.pull_request.number }} --body "$review"
        done < changed_files.txt
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}