name: GPT Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install OpenAI library
        run: pip install openai

      - name: Run GPT Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # 동적으로 base와 head 커밋 가져오기
          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${{ github.event.pull_request.head.sha }}"

          # 변경된 파일 목록 가져오기
          git diff --name-only "$base_sha" "$head_sha" > changed_files.txt

          # 변경된 파일들을 리뷰
          while IFS= read -r file; do
            echo "Reviewing file: $file"
            review=$(python3 gpt_code_review.py "$file")
            echo "$review"
            gh pr comment ${{ github.event.pull_request.number }} --body "$review"
          done < changed_files.txt